### ISSUE TITLE
What are adata_rna_sel and adata_atac_sel ?

### ISSUE THREAD

**Issue by DylanMannKrzisnik** [myylee/benchmark_sc_multiomic_integration#1]
Hi,

Thank you for this material. In the first code block `evaluate_vary_situations_public.ipynb`, what do `adata_rna_sel` and `adata_atac_sel` refer to? Is it ok to simply provide `adata_rna` and `adata_atac` to the `data_simulation` function?

**Comment by myylee** [comment]
Thanks for pointing out the typo. Yes, you could directly pass adata_rna and adata_atac to data_simulation function.

**Comment by DylanMannKrzisnik** [comment]
Thank you for your reply, much appreciated.
